- isolate.py
- 完成指令產生器的建置，可使用 `generate_isolate_run_command`、`generate_isolate_init_command` 與 `generate_isolate_cleanup_command` 這三個 function 來產出屬於 `isolate` 的指令。
> 完成指令產生器的建置

- isolate.py
- sandbox_be.py
- sandbox_enum.py
- 重構了 `do_work()` 的程式碼，包含意義不明的命名規則。
- 重構了 `pop_work()` 的程式碼，包含意義不明的命名規則。
> 重構 sandbox_be.py 的程式碼

- backend/tests/test.py
- backend/utils/isolate.py
- backend/utils/sandbox_enum.py
- example_code/code.go
- example_code/solution.go
- 新增沙盒對於 Golang 語言的支持，可評測 Golang 語言。
> 新增 Sandbox 對於 Golang 的支持

- backend/app.py
- backend/route/swagger/route.py
- backend/swagger/page.html
- backend/swagger/spec.json
在這份 PR 中，我們新增了 Swagger 頁面，來呈現 `/judge` 介面的相關規範，以利於重構。
> 新增 Swagger 頁面以利於呈現 `/judge` 介面

- .pre-commit-config.yaml
在這份 PR 中，我們新增 pre-commit 來保持每次提交時能夠符合規範（Black 格式與沒有尾端空白）。
> 新增 pre-commit 來保持每次提交符合規範

- .gitignore
在這份 PR 中，我們利用了 [gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore) 專案更新了 `.gitignore`。
> 利用 gitignore 專案更新 `.gitignore`

- backend/api/judge/route.py
- backend/api/judge/sandbox_util.py
- backend/api/system/route.py
- backend/app.py
在這份 PR 中，我們將 `sandbox_util.py` 內的全域變數移至 Application Config 內，讓不同的 Application 能夠記載不同的 Submission List 等相關的資訊，並不會讓其發生衝突。
> 提取全域變數並將其移至 Application Config 內

- backend/api/judge/isolate.py
- backend/api/judge/route.py
- backend/api/judge/route_util.py
- backend/api/judge/sandbox_enum.py
- backend/api/judge/sandbox_util.py
- backend/tests/conftest.py
- backend/tests/test.py
在這份 PR 中，我重構了 `sandbox_util.py`，並重構了不合理的設計，並且簡潔化了輸出。
> 重構 `sandbox_util.py` 

- requirements.txt
在這份 PR 中，我們新增了 freezegun 套件來測試有需要 timestamp 的函式。
> 新增 freezegun 套件以利於測試

- Dockerfile
- backend/env_doctor.sh
- env_doctor.sh
> 增加在Docker部屬時先確認isolate支援

- backend/tests/utils/isolate/test_util.py
- backend/utils/isolate/util.py
在這份 PR 中，我們定義了編譯的 `meta` 名稱，從 `meta.mt` 變成了每個運行的步驟都有獨立且唯一的檔案。
> 定義編譯的 `meta` 名稱

- backend/tests/conftest.py
- backend/tests/test_code/checker_memory_out_code.cpp
- backend/tests/test_code/out_of_memory_code.cpp
- backend/tests/utils/sandbox/running/test_util.py
- backend/utils/sandbox/enum.py
- backend/utils/sandbox/running/util.py
在這份 PR 中，我們讓 Sandbox 處理 `MLE`, `SMLE`, `CMLE` 的情況，並且將其納入自動化測試中。
> 讓 Sandbox 處理 `MLE`, `SMLE`, `CMLE` 的情況

- README.md
在這份 PR 中，我們嘗試更新了 `README.md`，移除過時的內容並將介紹、環境與安裝過程撰寫至 `README.md` 上。
> 更新 `README.md`

- backend/setting.json
- backend/setting/util.py
- backend/tests/conftest.py
- backend/tests/setting/test_setting.py
在這份 PR 中，我們完成了 setting 中 compiler 欄位的製作，預計使用其欄位來讓使用者自定義編譯器相關參數（指定檔案名稱、編譯參數與執行參數）
> 完成 setting 中 compiler 欄位的製作

- backend/setting.json
- backend/setting/util.py
- backend/tests/api/judge/test_route.py
- backend/tests/conftest.py
- backend/tests/setting/test_setting.py
- backend/tests/utils/isolate/test_util.py
- backend/tests/utils/sandbox/initialize/test_util.py
- backend/tests/utils/sandbox/running/test_util.py
- backend/utils/isolate/util.py
- backend/utils/sandbox/enum.py
在這份 PR 中，我們完成了自定義 compiler 的功能，並且遷移了測試來符合目前因應新功能所做的調整。
這個 PR 不包含針對於編譯器進行限制的功能。
> 完成自定義 compiler 的功能，不包含針對於編譯器進行限制的功能

- README.md
在這份 PR 中，我們修復了 `README.md` 的錯誤資訊，包含了錯字與補充 downgrade 方法僅適用在 Linux 平台上。
> 修復 `README.md` 的錯誤資訊

- .github/workflows/docker_workflow.yml
- backend/env_doctor.sh
- backend/env_setting.py
在這份 PR 中，我在env_doctor中增加了驗證Swap、ASLR、THP 設定的功能，並且優化了env_setting.py的執行流程
> 優化環境設定的腳本並且新增了doctor的驗證項目

- backend/tests/cg/api/judge/test_route.py
- backend/tests/cg/setting/test_setting.py
- backend/tests/cg/storage/test_util.py
- backend/tests/cg/utils/isolate/test_util.py
- backend/tests/cg/utils/sandbox/finish/test_util.py
- backend/tests/cg/utils/sandbox/initialize/test_util.py
- backend/tests/cg/utils/sandbox/running/test_util.py
- docker-compose.yml
> 整合 CG 測試中略過測試的條件

- backend/api/judge/util.py
- backend/tests/nocg/utils/sandbox/initialize/test_util.py
- backend/tests/nocg/utils/sandbox/running/test_util.py
- backend/utils/sandbox/inititalize/util.py
- backend/utils/sandbox/running/util.py
- backend/utils/sandbox/util.py
在這個 PR 中，我們修復了誤估 static-file 中測試資料大小的問題。
> 修復誤估測試資料大小

- backend/setting/util.py
- backend/tests/nocg/setting/test_setting.py
- backend/tests/nocg/utils/sandbox/initialize/test_util.py
- backend/utils/isolate/util.py
在這份 PR 中，我們透過補齊測資與刪除多餘函數來提昇了 code coverage。
目前的 code coverage 為 `98%`
> 增進目前的 code coverage

- backend/api/judge/util.py
在這份 PR 中，我在 Webhook 上新增時限，避免在 Webhook 無法被訪問時造成卡死。
> 在 Webhook 上新增時限

- backend/api/judge/util.py
在這份 PR 中，我新增了`tracker_id` 至多執行緒評測結果上。
> 新增 `tracker_id` 至多執行緒評測結果

- backend/api/judge/util.py
- backend/api/test/route.py
- backend/tests/nocg/api/judge/test_route.py
- backend/utils/sandbox/util.py
在這份 PR 中，我們新增了 Initialize Signal Webhook 用於方便瞭解 Initialize 開始時的時間點。
> 新增 Initialize Signal Webhook 
